version: "3"

services:
  frp:
    image: superng6/frp
    container_name: frp
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      # 通过ENV判断frpc、frps
      - FRP=frpc
    volumes:
      - $PWD/config:/config
    ports:
      - 6800:6800
    restart: unless-stopped  